#this R script will use resultant table generated by get_seq_lengths.py.
#then this this R script will convert the table in to a binary matrix
#so that it can tell which gene is present (1) or absent (0) of each sample.
# Note: If there was no sequence for a gene, a 0 is entered.

# usually the file will be names as "xxx_seq_lengths.txt"
file <- list.files(".", pattern="seq_length.txt$", full.names=T)
group <- sub("seq_length.txt", "", basename(file[1]))

dat <- read.table(file[1], sep="\t", header=T, stringsAsFactors=F)

bf <- function(x){ifelse(x==0,0,1)}

#remove mean length row
data <- dat[-1,]

#using the sample name as rowname
row.names(data)  <- data[,1]
data <- data[,-1]

#covert the matrix into binary
dd <- sapply(data,bf)
row.names(dd) <- row.names(data)

write.csv(dd, paste0(group, "_gene_sample_absent_prsent_matrix.csv", sep=""), quote=F)
